### ISSUE TITLE
Issue starting mongo server fixture

### ISSUE THREAD

**Issue by bmoscon** [manahl/pytest-plugins#127]
Python 3.7, macOS

```
Traceback (most recent call last):
  File "/anaconda3/envs/arctic/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/config/__init__.py", line 56, in main
    config = _prepareconfig(args, plugins)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/config/__init__.py", line 193, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/config/__init__.py", line 663, in pytest_cmdline_parse
    self.parse(args)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/config/__init__.py", line 835, in parse
    self._preparse(args, addopts=addopts)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/_pytest/config/__init__.py", line 787, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/envs/arctic/lib/python3.7/site-packages/pytest_server_fixtures/__init__.py", line 38, in <module>
    DEFAULT_SERVER_FIXTURES_HOSTNAME = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by bmoscon** [comment]
fixed
