### ISSUE TITLE
[Version 1.1.0] Pytest exception in thread after tests are run

### ISSUE THREAD

**Issue by Daenyth** [manahl/pytest-plugins#21]
After all my tests run, I get this output:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/environment/local/lib/python2.7/site-packages/pytest_server_fixtures/base.py", line 46, in run
    if not isinstance(l, string_types):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

I'm using a custom fixture class I wrote to bring up postgres;

``` python
# conftest.py

@pytest.fixture(scope='session')  # pylint: disable=no-member
def postgres_server_sess(request):
    """ Postgres server with session scope
    """
    server = _postgres_server(request)
    return server

def _postgres_server(request):
    """Take a pytest fixture request and set up a postgres server for it"""
    test_server = PostgresServer()

    _getconn = mock.patch('app.connection_pool.getconn,
                          side_effect=lambda: test_server.connect('db_name'))
    _putconn = mock.patch('app.connection_pool.putconn',
                          side_effect=lambda conn: conn.close())
    _getconn.start()
    _putconn.start()
    request.addfinalizer(_getconn.stop)
    request.addfinalizer(_putconn.stop)

    # For orm session
    _connection_config = mock.patch.object(AppConfiguration, 'db_config',
                                           new_callable=PropertyMock,
                                           side_effect=lambda: dict(test_server.connection_config,
                                                                    password='',
                                                                    database='db_name'))

    _connection_config.start()
    request.addfinalizer(_connection_config.stop)

    test_server.start()
    request.addfinalizer(test_server.teardown)

    return test_server

class PostgresServer(TestServer):
    random_port = True

    def kill(self, retries=5):
        if hasattr(self, 'pid'):
            os.kill(self.pid, self.kill_signal)

    def pre_setup(self):
        (self.workspace / 'db').mkdir()  # pylint: disable=no-value-for-parameter

        self.pg_bin = subprocess.check_output(["pg_config", "--bindir"]).rstrip()
        subprocess.check_call([
            self.pg_bin + '/initdb',
            str(self.workspace / 'db')
        ])
        logger.debug("pg_bin = %s", self.pg_bin)

        self.connection_config = {
            u'host': u'localhost',
            u'user': os.environ['USER'],
            u'port': self.port,
            u'connect_timeout': 3,  # In seconds
        }
        self.delete = True

    def post_setup(self):
        set_up_schema_and_migrations()

    @property
    def run_cmd(self):
        logger.debug("Starting postgres")
        return [
            self.pg_bin + '/postgres',
            '-F',
            '-k', str(self.workspace / 'db'),
            '-D', str(self.workspace / 'db'),
            '-p', str(self.port),
            # '-c', "log_destination=stderr"
        ]

    def check_server_up(self):
        try:
            print("Connecting to Postgres at localhost:{}".format(self.port))
            with self.connect('postgres') as conn:
                conn.set_session(autocommit=True)
                with conn.cursor() as cursor:
                    cursor.execute("CREATE DATABASE db_name")
            self.connection = self.connect('db_name')
            with open(self.workspace / 'db' / 'postmaster.pid', 'r') as f:
                self.pid = int(f.readline().rstrip())
            return True
        except OperationalError as e:
            logger.warn("Could not connect to test postgres: %s", str(e))
        return False

    def connect(self, database):
        return psycopg2.connect(database=database, **self.connection_config)
```

**Comment by eeaston** [comment]
Hi there - sorry for the terribly long delay in responding :( 
I really like your postgres fixture! Would you like me to add it to the repository as part of pytest-server-fixtures, or a separate package pytest-postgresql? I'll sort out making it work across all the pyversions, perhaps could you submit a PR which has some tests in it?

**Comment by Daenyth** [comment]
But once I do that, then yes I'll pr it in

**Comment by Daenyth** [comment]
I'd like to refactor it first

**Comment by eeaston** [comment]
Okiedokie, I'll wait for the PR.

**Comment by eeaston** [comment]
Closing this issue as we've merged the postgres fixture into master.
