### ISSUE TITLE
Can't install pytest-server-fixtures 1.2.11 on OSX

### ISSUE THREAD

**Issue by Daenyth** [manahl/pytest-plugins#62]
I get this error - seems to be related to pytest-shutil
```
Command "/Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-_fl5ht7f-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/daenyth/Curata/observer/.tox/unit/bin/../include/site/python3.6/pytest-shutil" failed with error code 1 in /private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/
```

<details>
<summary>pip freeze</summary>

```
aiopg==0.13.0
amazon-kclpy==1.4.5
apipkg==1.4
APScheduler==3.3.1
boto==2.48.0
boto3==1.4.4
botocore==1.5.86
contextlib2==0.5.5
coverage==4.4.1
docutils==0.13.1
execnet==1.4.1
hypothesis==3.1.0
jmespath==0.9.3
mock==2.0.0
path.py==10.3.1
pbr==3.1.1
protobuf==3.3.0
psycopg2==2.7.3
py==1.4.34
pyhocon==0.3.35
pyparsing==2.2.0
pytest==3.1.3
pytest-asyncio==0.6.0
pytest-cov==2.5.1
python-dateutil==2.6.1
pytz==2017.2
raven==6.1.0
redis==2.10.5
s3transfer==0.1.10
six==1.10.0
SQLAlchemy==1.1.11
tzlocal==1.4
```
</details>

<details>
<summary>
Full stack trace from pip install</summary>

```
pip install pytest-server-fixtures
Collecting pytest-server-fixtures
  Using cached pytest-server-fixtures-1.2.11.tar.gz
Requirement already satisfied: pytest in ./.tox/unit/lib/python3.6/site-packages (from pytest-server-fixtures)
Collecting pytest-shutil (from pytest-server-fixtures)
  Using cached pytest-shutil-1.2.11.tar.gz
Collecting pytest-fixture-config (from pytest-server-fixtures)
  Using cached pytest-fixture-config-1.2.11.tar.gz
Requirement already satisfied: six in ./.tox/unit/lib/python3.6/site-packages (from pytest-server-fixtures)
Collecting requests (from pytest-server-fixtures)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.tox/unit/lib/python3.6/site-packages (from pytest->pytest-server-fixtures)
Requirement already satisfied: py>=1.4.33 in ./.tox/unit/lib/python3.6/site-packages (from pytest->pytest-server-fixtures)
Requirement already satisfied: execnet in ./.tox/unit/lib/python3.6/site-packages (from pytest-shutil->pytest-server-fixtures)
Requirement already satisfied: contextlib2 in ./.tox/unit/lib/python3.6/site-packages (from pytest-shutil->pytest-server-fixtures)
Requirement already satisfied: path.py in ./.tox/unit/lib/python3.6/site-packages (from pytest-shutil->pytest-server-fixtures)
Requirement already satisfied: mock in ./.tox/unit/lib/python3.6/site-packages (from pytest-shutil->pytest-server-fixtures)
Collecting certifi>=2017.4.17 (from requests->pytest-server-fixtures)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->pytest-server-fixtures)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests->pytest-server-fixtures)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests->pytest-server-fixtures)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Requirement already satisfied: apipkg>=1.4 in ./.tox/unit/lib/python3.6/site-packages (from execnet->pytest-shutil->pytest-server-fixtures)
Requirement already satisfied: pbr>=0.11 in ./.tox/unit/lib/python3.6/site-packages (from mock->pytest-shutil->pytest-server-fixtures)
Building wheels for collected packages: pytest-server-fixtures, pytest-shutil, pytest-fixture-config
  Building wheel for pytest-server-fixtures failed: [Errno 13] Permission denied: '/Users/daenyth/Library/Caches/pip/wheels/d5/8e'
  Running setup.py bdist_wheel for pytest-shutil ... error
  Complete output from command /Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/tmpd95io9zhpip-wheel- --python-tag cp36:
  Traceback (most recent call last):
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 488, in fetch_build_egg
      cmd = self._egg_fetcher
  AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py", line 53, in <module>
      setup(**kwargs)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 444, in fetch_build_eggs
      replace_conflicting=True,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1126, in best_match
      return self.obtain(req, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1138, in obtain
      return installer(requirement)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_egg
      cmd.ensure_finalized()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 333, in finalize_options
      self.index_url, search_path=self.shadow_path, hosts=hosts,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/package_index.py", line 306, in __init__
      and (ca_bundle or ssl_support.find_ca_bundle())
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 247, in find_ca_bundle
      or _certifi_where()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 253, in _certifi_where
      return __import__('certifi').where()
  AttributeError: module 'certifi' has no attribute 'where'

  ----------------------------------------
  Failed building wheel for pytest-shutil
  Running setup.py clean for pytest-shutil
  Complete output from command /Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 488, in fetch_build_egg
      cmd = self._egg_fetcher
  AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py", line 53, in <module>
      setup(**kwargs)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 444, in fetch_build_eggs
      replace_conflicting=True,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1126, in best_match
      return self.obtain(req, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1138, in obtain
      return installer(requirement)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_egg
      cmd.ensure_finalized()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 333, in finalize_options
      self.index_url, search_path=self.shadow_path, hosts=hosts,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/package_index.py", line 306, in __init__
      and (ca_bundle or ssl_support.find_ca_bundle())
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 247, in find_ca_bundle
      or _certifi_where()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 253, in _certifi_where
      return __import__('certifi').where()
  AttributeError: module 'certifi' has no attribute 'where'

  ----------------------------------------
  Failed cleaning build dir for pytest-shutil
  Running setup.py bdist_wheel for pytest-fixture-config ... error
  Complete output from command /Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-fixture-config/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/tmphnw4i2eepip-wheel- --python-tag cp36:
  Traceback (most recent call last):
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 488, in fetch_build_egg
      cmd = self._egg_fetcher
  AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-fixture-config/setup.py", line 40, in <module>
      setup(**kwargs)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 444, in fetch_build_eggs
      replace_conflicting=True,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1126, in best_match
      return self.obtain(req, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1138, in obtain
      return installer(requirement)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_egg
      cmd.ensure_finalized()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 333, in finalize_options
      self.index_url, search_path=self.shadow_path, hosts=hosts,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/package_index.py", line 306, in __init__
      and (ca_bundle or ssl_support.find_ca_bundle())
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 247, in find_ca_bundle
      or _certifi_where()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 253, in _certifi_where
      return __import__('certifi').where()
  AttributeError: module 'certifi' has no attribute 'where'

  ----------------------------------------
  Failed building wheel for pytest-fixture-config
  Running setup.py clean for pytest-fixture-config
  Complete output from command /Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-fixture-config/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 488, in fetch_build_egg
      cmd = self._egg_fetcher
  AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-fixture-config/setup.py", line 40, in <module>
      setup(**kwargs)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 444, in fetch_build_eggs
      replace_conflicting=True,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1126, in best_match
      return self.obtain(req, installer)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1138, in obtain
      return installer(requirement)
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_egg
      cmd.ensure_finalized()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 333, in finalize_options
      self.index_url, search_path=self.shadow_path, hosts=hosts,
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/package_index.py", line 306, in __init__
      and (ca_bundle or ssl_support.find_ca_bundle())
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 247, in find_ca_bundle
      or _certifi_where()
    File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 253, in _certifi_where
      return __import__('certifi').where()
  AttributeError: module 'certifi' has no attribute 'where'

  ----------------------------------------
  Failed cleaning build dir for pytest-fixture-config
Failed to build pytest-server-fixtures pytest-shutil pytest-fixture-config
Installing collected packages: pytest-shutil, pytest-fixture-config, certifi, chardet, idna, urllib3, requests, pytest-server-fixtures
  Running setup.py install for pytest-shutil ... error
    Complete output from command /Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-_fl5ht7f-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/daenyth/Curata/observer/.tox/unit/bin/../include/site/python3.6/pytest-shutil:
    Traceback (most recent call last):
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 488, in fetch_build_egg
        cmd = self._egg_fetcher
    AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py", line 53, in <module>
        setup(**kwargs)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 444, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1126, in best_match
        return self.obtain(req, installer)
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1138, in obtain
        return installer(requirement)
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_egg
        cmd.ensure_finalized()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 333, in finalize_options
        self.index_url, search_path=self.shadow_path, hosts=hosts,
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/package_index.py", line 306, in __init__
        and (ca_bundle or ssl_support.find_ca_bundle())
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 247, in find_ca_bundle
        or _certifi_where()
      File "/Users/daenyth/Curata/observer/.tox/unit/lib/python3.6/site-packages/setuptools/ssl_support.py", line 253, in _certifi_where
        return __import__('certifi').where()
    AttributeError: module 'certifi' has no attribute 'where'

    ----------------------------------------
Command "/Users/daenyth/Curata/observer/.tox/unit/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-_fl5ht7f-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/daenyth/Curata/observer/.tox/unit/bin/../include/site/python3.6/pytest-shutil" failed with error code 1 in /private/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/pip-build-g9gqwg4u/pytest-shutil/
(unit) alpha!observer * $>

```
</details>

**Comment by Daenyth** [comment]
Strange; I was able to install things one at a time and then it seemed to work. But still, running `tox -r` for me fails like this.

**Comment by Daenyth** [comment]
Changing my dev dependencies to `'pytest-shutil<1.2.11', 'pytest-server-fixtures'` lets it install actually. So I think the issue is with the latest pytest-shutil

**Comment by bmoscon** [comment]
gonna update the issue title then so its obvious that the issue is with latest pytest-shutil on OSX. (That is correct, isnt it?)

**Comment by bmoscon** [comment]
I had zero issue installing pytest-server-fixtures (latest) or pytest-shutil on OSX. None of those errors look related to any of the fixtures, they're all setuptools/distutils/certifi related.

**Comment by Daenyth** [comment]
How can I narrow down the issue? I'm just using the homebrew installed python3

**Comment by bmoscon** [comment]
I'm not sure. I assume you can manually pip install it just fine? It seems like its a tox thing, or its something to do with the command you are running, or its a version issue with something else you have.

**Comment by bmoscon** [comment]
if you look at what changed between the last two versions, its almost nothing for pytest-shutil
